### ISSUE TITLE
ImportError: cannot import name 'project' from 'DagAmendment.Accel' (unknown location)

### ISSUE THREAD

**Issue by hful** [eliemichel/DagAmendment#6]
bpy.context.space_data.recent_folders_active = 1
bpy.context.space_data.system_folders_active = 3
bpy.context.space_data.system_folders_active = 3
bpy.context.space_data.params.filename = ""
bpy.context.space_data.recent_folders_active = 1
Modules Installed (DagAmendment) from 'D:\\DagAmendment-v1.1.1.zip' into 'C:\\Users\\xxx\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DagAmendment\__init__.py", line 81, in <module>
    from . import properties
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DagAmendment\properties.py", line 33, in <module>
    from .SamplePoints import SamplePoints
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DagAmendment\SamplePoints.py", line 32, in <module>
    from .uv_coparam import coparam_to_position
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DagAmendment\uv_coparam.py", line 35, in <module>
    from .Accel import project as project_on_mesh
ImportError: cannot import name 'project' from 'DagAmendment.Accel' (unknown location)

**Comment by eliemichel** [comment]
Do you confirm that you see the Accel binary in the installed add-on? 
![image](https://github.com/eliemichel/DagAmendment/assets/5802849/d2ef0a74-7339-49a1-a12a-0957aeac696c)

The "cp310" part must match the version of Python used by your version of Blender (I don't remember which one exactly Blender 3.1 uses but I believe it is either 3.10 or 3.9 so it should be ok).

Do you use a 64bit installation of Blender? You can check your very version of Blender's Python in the Scripting layout tab:
![image](https://github.com/eliemichel/DagAmendment/assets/5802849/c541a402-45de-44f8-9677-ab806080acd4)
